/**
 * reportPdf.js
 * ─────────────────────────────────────────────────────────────────
 * Render a Markdown civic report into a professionally formatted PDF
 * using jsPDF only (no html2canvas — that avoids Tailwind v4 `oklch`
 * colour parsing issues and keeps the output crisp/vector text).
 *
 * Supported Markdown:
 *   # / ## / ###    headings
 *   - or *          bullet lists
 *   1. 2. 3.        numbered lists
 *   **bold**        inline bold (markers stripped, rendered bold)
 *   ---             horizontal rule
 *   | a | b |       tables (rendered as simple key/value style rows)
 *   plain text      wrapped paragraphs
 * ─────────────────────────────────────────────────────────────────
 */

import jsPDF from 'jspdf';

// Layout constants (mm, A4 portrait)
const PAGE = { w: 210, h: 297 };
const MARGIN = { top: 22, bottom: 18, left: 18, right: 18 };
const CONTENT_W = PAGE.w - MARGIN.left - MARGIN.right;

const COLOR = {
  ink:    [30, 41, 59],    // slate-800
  muted:  [100, 116, 139], // slate-500
  accent: [37, 99, 235],   // blue-600
  rule:   [203, 213, 225], // slate-300
  band:   [15, 23, 42],    // slate-900
};

/** Strip inline markdown markers we don't render specially. */
function cleanInline(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1') // bold
    .replace(/\*(.+?)\*/g, '$1')     // italic
    .replace(/`(.+?)`/g, '$1')       // inline code
    .replace(/^#+\s*/, '')           // stray heading markers
    .trim();
}

/**
 * Generate and trigger download of the PDF.
 * @param {string} markdown   the AI-generated report body
 * @param {object} meta       { timeRange, generatedAt }
 */
export function downloadReportPdf(markdown, meta = {}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = MARGIN.top;

  // ── Header band ───────────────────────────────────────────────
  doc.setFillColor(...COLOR.band);
  doc.rect(0, 0, PAGE.w, 16, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('AI Road Analytics Platform', MARGIN.left, 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Municipal Road Infrastructure Report', PAGE.w - MARGIN.right, 10, { align: 'right' });

  // ── Sub-header meta line ──────────────────────────────────────
  y = 24;
  doc.setTextColor(...COLOR.muted);
  doc.setFontSize(9);
  const dateStr = meta.generatedAt
    ? new Date(meta.generatedAt).toLocaleString()
    : new Date().toLocaleString();
  doc.text(`Range: ${meta.timeRange || '—'}`, MARGIN.left, y);
  doc.text(`Generated by AI · ${dateStr}`, PAGE.w - MARGIN.right, y, { align: 'right' });
  y += 4;
  doc.setDrawColor(...COLOR.rule);
  doc.line(MARGIN.left, y, PAGE.w - MARGIN.right, y);
  y += 8;

  // ── Page-break helper ─────────────────────────────────────────
  const ensureSpace = (needed) => {
    if (y + needed > PAGE.h - MARGIN.bottom) {
      doc.addPage();
      y = MARGIN.top;
    }
  };

  const writeWrapped = (text, { size, style, color, indent = 0, gap }) => {
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, CONTENT_W - indent);
    const lineH = size * 0.42; // mm per line, tuned for readability
    for (const line of lines) {
      ensureSpace(lineH);
      doc.text(line, MARGIN.left + indent, y);
      y += lineH;
    }
    y += gap;
  };

  // ── Walk the markdown line by line ────────────────────────────
  const lines = (markdown || '').replace(/\r\n/g, '\n').split('\n');

  for (let raw of lines) {
    const line = raw.replace(/\s+$/g, '');

    if (!line.trim()) { y += 2; continue; } // blank line spacing

    // Horizontal rule
    if (/^\s*([-*_])\1{2,}\s*$/.test(line)) {
      ensureSpace(4);
      doc.setDrawColor(...COLOR.rule);
      doc.line(MARGIN.left, y, PAGE.w - MARGIN.right, y);
      y += 5;
      continue;
    }

    // Headings
    const h = line.match(/^(#{1,6})\s+(.*)$/);
    if (h) {
      const level = h[1].length;
      const text = cleanInline(h[2]);
      if (level === 1) {
        ensureSpace(10);
        writeWrapped(text, { size: 17, style: 'bold', color: COLOR.ink, gap: 3 });
      } else if (level === 2) {
        ensureSpace(8);
        writeWrapped(text, { size: 13, style: 'bold', color: COLOR.accent, gap: 2.5 });
      } else {
        ensureSpace(7);
        writeWrapped(text, { size: 11, style: 'bold', color: COLOR.ink, gap: 2 });
      }
      continue;
    }

    // Table rows → render as plain piped text (skip separator rows)
    if (/^\s*\|.*\|\s*$/.test(line)) {
      if (/^\s*\|[\s:|-]+\|\s*$/.test(line)) continue; // separator
      const cells = line.split('|').map((c) => cleanInline(c)).filter((c) => c !== '');
      writeWrapped(cells.join('   ·   '), { size: 9.5, style: 'normal', color: COLOR.ink, indent: 2, gap: 1 });
      continue;
    }

    // Bullet list
    const bullet = line.match(/^\s*[-*]\s+(.*)$/);
    if (bullet) {
      writeWrapped(`•  ${cleanInline(bullet[1])}`, { size: 10, style: 'normal', color: COLOR.ink, indent: 4, gap: 1 });
      continue;
    }

    // Numbered list
    const numbered = line.match(/^\s*(\d+)\.\s+(.*)$/);
    if (numbered) {
      writeWrapped(`${numbered[1]}.  ${cleanInline(numbered[2])}`, { size: 10, style: 'normal', color: COLOR.ink, indent: 4, gap: 1 });
      continue;
    }

    // Paragraph
    writeWrapped(cleanInline(line), { size: 10, style: 'normal', color: COLOR.ink, gap: 2 });
  }

  // ── Footer page numbers ───────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...COLOR.muted);
    doc.text(
      `Page ${i} of ${pageCount}`,
      PAGE.w - MARGIN.right,
      PAGE.h - 8,
      { align: 'right' }
    );
    doc.text('Generated by AI · Not a substitute for on-site inspection', MARGIN.left, PAGE.h - 8);
  }

  // ── Filename: Road_Report_YYYY_MM_DD.pdf ──────────────────────
  const d = meta.generatedAt ? new Date(meta.generatedAt) : new Date();
  const pad = (n) => String(n).padStart(2, '0');
  const fname = `Road_Report_${d.getFullYear()}_${pad(d.getMonth() + 1)}_${pad(d.getDate())}.pdf`;
  doc.save(fname);
}
